export const BUY_LAPTOP = "BUY_LAPTOP";
export const BUY_MOBILE = "BUY_MOBILE";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
